# Generated by Django 4.1.1 on 2023-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todotasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_pc',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
