# Generated by Django 4.1.1 on 2023-04-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
